# Generated by Django 4.1.1 on 2022-09-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_texto_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
