# Generated by Django 4.1.1 on 2022-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_texto_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='link',
            field=models.TextField(),
        ),
    ]
