# Generated by Django 4.1.1 on 2022-10-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_texto_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='resumo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
