# Generated by Django 4.1.1 on 2022-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_texto_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='texto',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
