# Generated by Django 4.1.1 on 2022-10-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_texto_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
