# Generated by Django 4.0.6 on 2022-11-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePortal', models.CharField(max_length=100)),
                ('filtroTexto', models.CharField(max_length=1000)),
            ],
        ),
    ]
