# Generated by Django 4.1.1 on 2022-10-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_texto_link_alter_texto_resumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texto',
            name='resumo',
        ),
    ]
