# Generated by Django 4.1.1 on 2022-10-27 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_dados_delete_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dados',
        ),
    ]
