# Generated by Django 4.1.1 on 2022-10-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dados',
        ),
    ]
