# Generated by Django 4.1.1 on 2022-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePortal', models.CharField(max_length=100)),
                ('filtroTexto', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='dados',
        ),
    ]
